######################################################################
# Automatically generated by qmake (2.01a) lun. nov. 15 07:44:54 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += abuleduaproposv0.h mainwindow.h tete.h
FORMS += mainwindow.ui \
    abuleduaproposv0.ui
SOURCES += abuleduaproposv0.cpp main.cpp mainwindow.cpp tete.cpp
RESOURCES += NombreCible.qrc
QT += script xml network
