.TH leterrier-cibler 1 "January 15, 2015"
.SH NAME
leterrier\-Nombre\-Cible \- three numbers to hit the target 
.SH SYNOPSIS
.B leterrier\-Nombre\-Cible
.SH DESCRIPTION
is a program for numeric entertainement. Will you be able to hit the target with three numbers ?
.PP

leterrier\-Nombre\-Cible (1)
.SH AUTHOR
This manual page and the script were written by Jean-Louis Frucot
<frucot.jeanlouis@free.fr>
